version: "3"
services:
  db: 
  web:
    build: .
    ports:
      - undefined:undefined
    links:
      - db
    depends_on:
      - db
    environment:
      MATERIA_MODE: "production"
      NO_HOST: "true"